### ISSUE TITLE
Adding in-browser support

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-the-bugs#84]
As I commented on Discord, now that Diddi and The Bugs 3.0.0 is out, it's a great moment to prepare web support for in-browser playing! This issue will track that process.

cc @HarshNarayanJha

**Comment by DiddiLeija** [comment]
I made a small investigation about how Pyxel works on the Web. I found this documentation:

- https://kitao.github.io/pyxel/wasm/launcher/
- https://kitao.github.io/pyxel/wasm/examples/index.html

BTW, I'm on the Pyxel's Discord server, so I'll try to find more info there too :)

**Comment by DiddiLeija** [comment]
> * https://kitao.github.io/pyxel/wasm/launcher/

Following the instructions from this article (at section "Run a Python script using Pyxel"), I prepared this link: **https://kitao.github.io/pyxel/wasm/launcher/?run=DiddiLeija.diddi-and-the-bugs...main**

It launches well on my browser, it finds the script, and it runs. However, when I press the key 1 (to start), it gets somehow stuck. Can somebody else confirm if the above link works?

**Comment by DiddiLeija** [comment]
> It launches well on my browser, it finds the script, and it runs. However, when I press the key 1 (to start), it gets somehow stuck.

Seems like I'll have to open an issue to Pyxel...

**Comment by DiddiLeija** [comment]
I tried to debug the "key 1 bug" using my browser's developer tools. I found this error raised just after the game gets stuck:

```
Uncaught RuntimeError: Aborted(emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.). Build with -sASSERTIONS for more info.
    at abort (pyodide.asm.js:10:165923)
    at assert (pyodide.asm.js:10:160949)
    at setMainLoop (pyodide.asm.js:10:310070)
    at _emscripten_set_main_loop_arg (pyodide.asm.js:10:666180)
    at invoke_viiii (pyodide.asm.js:10:1704948)
    at 00b31e16:0x1df54
    at invoke_viii (pyodide.asm.js:10:1705883)
    at 00b31e16:0x50b5b
    at method_call_trampoline (pyodide.asm.js:10:221844)
    at pyodide.asm.wasm:0x1619f4
```

I _think_ that's related to how we switch from the menu to the real game at `App.startup`:

https://github.com/DiddiLeija/diddi-and-the-bugs/blob/be6b689d5faccbae512c5a5d15227b8b51912375/main.py#L300-L307

We call `pyxel.run` each time we make the switch (see lines 303 and 307). And the error says:

```
there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.).
```

I'd suppose the "main loop" is activated by a `pyxel.run`? If so, this issue should be gone by finding a way to avoid calling that function more than once.

**Comment by DiddiLeija** [comment]
> I'd suppose the "main loop" is activated by a `pyxel.run`? If so, this issue should be gone by finding a way to avoid calling that function more than once.

I'll test this theory around the next days. I'll post the results here.

**Comment by DiddiLeija** [comment]
A while ago, I'll posted on Discord about this. Indeed, we can fix the code to enable web support. Let's test that!
